### PR TITLE
Support nested structures

### PR DESCRIPTION
**Pull request by ismaelga**
Related to #1

Any comment is welcome :heart:

### CODE REVIEW

**Comment by jtmoulia** [comment]
Super useful -- I'd love to see these changes make it in.

Disclaimer: I'm not the maintainer, but I think some readme or docstring docs/examples would be super useful.

**Comment by bruce** [comment]
:+1: I'll be reviewing this today :-)

**Comment by benwilson512** [comment]
Hey sorry for the delay, things have been busy. Can I ask why you've changed the @vex_validations attr from a keyword list to a map, and then are using the polymorphic Dict functions?

**Comment by ismaelga** [comment]
@benwilson512 np.

I had no good reason. Using Map now.

**Comment by benwilson512** [comment]
Sorry for the wait!

**Comment by ismaelga** [comment]
no problem. Thanks :+1:

**Pull request merged**
